name = "JamesPlots"
uuid = "65b38e5c-fa97-498f-814c-2dc0ae7de8a9"
authors = ["James Gardner <james.gardner1421@gmail.com> and contributors"]
version = "0.1.1"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
CairoMakie = "0.7, 0.8, 0.9, 0.10"
ColorSchemes = "3"
Colors = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
